AWSTemplateFormatVersion: '2010-09-09'

Description: >
  CSA Final Project
  Fullstack Serverless Architecture
  Frontend + Backend + Database + SNS

Parameters:

  LambdaRoleArn:
    Type: String
    Description: ARN dari LabRole

  NotificationEmail:
    Type: String
    Description: Email penerima notifikasi SNS

Resources:

  ProductsTable:

    Type: AWS::DynamoDB::Table

    Properties:

      TableName: Products

      BillingMode: PAY_PER_REQUEST

      AttributeDefinitions:

        - AttributeName: ProductId
          AttributeType: S

      KeySchema:

        - AttributeName: ProductId
          KeyType: HASH

  ProductNotificationTopic:

    Type: AWS::SNS::Topic

    Properties:

      TopicName: inventory-topic

  ProductSubscription:

    Type: AWS::SNS::Subscription

    Properties:

      TopicArn: !Ref ProductNotificationTopic

      Protocol: email

      Endpoint: !Ref NotificationEmail

  BackendLambda:

    Type: AWS::Lambda::Function

    Properties:

      FunctionName: products-api-v1

      Runtime: nodejs24.x

      Handler: index.handler

      MemorySize: 128

      Timeout: 3

      Role: !Ref LambdaRoleArn

      Code:

        S3Bucket: inventory-pro-project

        S3Key: backend.zip

      Environment:

        Variables:

          SNS_TOPIC_ARN: !Ref ProductNotificationTopic

          DB_API_BASE_URL: https://wnguaiqxtd.execute-api.us-east-1.amazonaws.com

  DatabaseLambda:

    Type: AWS::Lambda::Function

    Properties:

      FunctionName: database-lambda

      Runtime: nodejs24.x

      Handler: index.handler

      MemorySize: 128

      Timeout: 3

      Role: !Ref LambdaRoleArn

      Code:

        S3Bucket: inventory-pro-project

        S3Key: database-lambda.zip

  BackendHttpApi:

    Type: AWS::ApiGatewayV2::Api

    Properties:

      Name: BackendHttpApi

      ProtocolType: HTTP

  DatabaseHttpApi:

    Type: AWS::ApiGatewayV2::Api

    Properties:

      Name: DatabaseHttpApi

      ProtocolType: HTTP

  BackendIntegration:

    Type: AWS::ApiGatewayV2::Integration

    Properties:

      ApiId: !Ref BackendHttpApi

      IntegrationType: AWS_PROXY

      IntegrationUri: !GetAtt BackendLambda.Arn

      PayloadFormatVersion: "2.0"

  DatabaseIntegration:

    Type: AWS::ApiGatewayV2::Integration

    Properties:

      ApiId: !Ref DatabaseHttpApi

      IntegrationType: AWS_PROXY

      IntegrationUri: !GetAtt DatabaseLambda.Arn

      PayloadFormatVersion: "2.0"

  BackendRoute:

    Type: AWS::ApiGatewayV2::Route

    Properties:

      ApiId: !Ref BackendHttpApi

      RouteKey: "ANY /{proxy+}"

      Target: !Join
        - /
        - - integrations
          - !Ref BackendIntegration

  DatabaseRoute:

    Type: AWS::ApiGatewayV2::Route

    Properties:

      ApiId: !Ref DatabaseHttpApi

      RouteKey: "ANY /{proxy+}"

      Target: !Join
        - /
        - - integrations
          - !Ref DatabaseIntegration

  DatabaseRootRoute:

    Type: AWS::ApiGatewayV2::Route

    Properties:

      ApiId: !Ref DatabaseHttpApi

      RouteKey: "ANY /"

      Target: !Join
        - /
        - - integrations
          - !Ref DatabaseIntegration

  BackendStage:

    Type: AWS::ApiGatewayV2::Stage

    Properties:

      ApiId: !Ref BackendHttpApi

      StageName: "$default"

      AutoDeploy: true

  DatabaseStage:

    Type: AWS::ApiGatewayV2::Stage

    Properties:

      ApiId: !Ref DatabaseHttpApi

      StageName: "$default"

      AutoDeploy: true

  BackendLambdaPermission:

    Type: AWS::Lambda::Permission

    Properties:

      Action: lambda:InvokeFunction

      FunctionName: !Ref BackendLambda

      Principal: apigateway.amazonaws.com

      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${BackendHttpApi}/*

  DatabaseLambdaPermission:

    Type: AWS::Lambda::Permission

    Properties:

      Action: lambda:InvokeFunction

      FunctionName: !Ref DatabaseLambda

      Principal: apigateway.amazonaws.com

      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${DatabaseHttpApi}/*

Outputs:

  BackendApiUrl:

    Value: !Sub https://wnguaiqxtd.execute-api.us-east-1.amazonaws.com

  DatabaseApiUrl:

    Value: !Sub https://0voitt7vf1.execute-api.us-east-1.amazonaws.com

  ProductsTable:

    Value: !Ref ProductsTable

  SnsTopicArn:

    Value: !Ref ProductNotificationTopic